### ISSUE TITLE
SMS was not silent when sent to blackberry bold

### ISSUE THREAD

**Issue by GMNX** [itds-consulting/android-silent-ping-sms#15]
![img_20171206_165818](https://user-images.githubusercontent.com/1034622/33656144-c56c2952-daa7-11e7-9f5b-076d3afab91b.jpg)

there was a random char read by blackberry. but, when I sent to another device(lenovo P70-a) it was sient, no notification at all.

is that blackberry an exception for this app?

**Comment by smarek** [comment]
Might be, we've actually didn't test with Blackberry devices, as we do not have these available.
What was your idea, sending from Android or from Blackberry device?

**Comment by GMNX** [comment]
I'm sending from redmi 4x to blackberry bold. since the blackberry device is not using android, so I can't install into blackberry

**Comment by GMNX** [comment]
I Have check sent to my old phone(motorola 123), it's reading the sms like in the blackberry. I haven't read the PDU format of SMS. But, from what I know silent SMS is using type 0 from GSM 03.04

![selection_045](https://user-images.githubusercontent.com/1034622/33701839-48afe618-db53-11e7-94b9-369215980c1b.png)

So, are you sent the type 0?
I haven't fully understand about SMS binary
can you explain the payload?
So, we can analyze what we send

**Comment by smarek** [comment]
Sure, this is not "Type 0" message, because that would require rooted Android device to send RAW SMS PDU through the RIL. Android does not allow this by default.

This is application specific message, which on most of the phones is consumed and not shown in messaging (sms) application, because it is not standard "Short Message". It targets application running in RIL on usually not-used port (like TCP port), so the RIL will consume the message and provide only ACK (delivery report).

Mobile phones that do not support "data messages" (application binary messages), will try to decode the SMS as standard SMS-DELIVER PDU, which will result in ASCII rubish being displayed.

Method used is [SmsManager.sendDataMessage](https://developer.android.com/reference/android/telephony/SmsManager.html)

```java
SmsManager.getDefault().sendDataMessage(phoneNumber.getText().toString(), null, (short) 9200, payload, sentPI, deliveryPI);
```

Which simply sends the message to remote MS to port 9200, with binary payload, as specified in README.

**Comment by smarek** [comment]
Also note that purpose of this project was not "sending Type 0 messages", but demonstrating that it's not only "Type 0" message (which some PLMNs block already), that can be used to track / attack the remote device.

**Comment by GMNX** [comment]
oh i see.. thanks @smarek for your explanation

That means, this app will not working if the target using Mobile phones that do not support "data messages"

or is that any other possibility to targeting older phone and not showing any ASCII rubish?

**Comment by smarek** [comment]
Without rooting the Android phone and having both HPLMN and VPLMN not filtering Type0 messages, i don't think so.
You can however play with the payload, might do something different depending on phone type and operator network filtering rules. Will cost you (if you don't play on your own network) some SMSs :)

**Comment by GMNX** [comment]
can you explain, the payload that we used? 
`byte[]{0x0A, 0x06, 0x03, (byte) 0xB0, (byte) 0xAF, (byte) 0x82, 0x03, 0x06, 0x6A, 0x00, 0x05}`

why did you write payload that way? have you any specific intention in the payload?
I'm afraid if messed up the payload and your intention in the payload was not achieved

and when we got ACK, is there any other usefull information beside phone is online?

sorry if I ask to many question. i'm just curios to know about silent sms :)
