### ISSUE TITLE
Error sending from Verizon note 4 rr remix

### ISSUE THREAD

**Issue by Lantz1963** [itds-consulting/android-silent-ping-sms#8]
When I try open app it has a pre defined number I have tried putting the number I wanted to ping in front of this number, behind it, erasing predefined number and using only the number I want to ping all results in send error. Am I missing something? Thanks

**Comment by smarek** [comment]
Hey, you delete the number that is pre-filled (including the +420 prefix for czech republic) and fill in the number (preferably including your country prefix) you want to ping.

However what your problem is, that every attempt ends up with "send error", that means, it was not possible to send the modified SMS PDU contents through your OS.

Could you please provide more debug info, such as device version, Android version (including possible updates), so we can work out why the problems?

**Comment by smarek** [comment]
No response from @Lantz1963  for a few months, closing
